backend:
  name: git-gateway
  branch: master

media_folder: "public/uploads"
public_folder: "/uploads"

collections:
  - name: "gallery"
    label: "Galer√≠a"
    folder: "public/uploads"
    create: true
    delete: false
    slug: "{{filename}}"
    fields:
      - { label: "Imagen", name: "image", widget: "image" }
